#ESPIDF= /d/fftust/project/micropython-esp32-new/esp-idf
ESPIDF= /d/fftust/project/mic-ESP32/esp32_pro/esp-idf
#PORT = /dev/ttyS2
PORT = /COM6
FLASH_MODE = dio
#FLASH_SIZE = 4MB
#CROSS_COMPILE = xtensa-esp32-elf-

include GNUMakefile